global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'content-api'
    static_configs:
      - targets: ['content-api:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
    metrics_path: /metrics
    scrape_interval: 10s